create header and navbar
GSG-G11/Tashteeb pull request #10
Opened 2022-04-28 15:47 UTC by mo7amedehab97

create header and navbar relates #5 

![Screenshot from 2022-04-28 18-41-22](https://user-images.githubusercontent.com/61945138/165792159-9809915f-0158-44aa-bc8a-57efe86fc122.png)

2022-04-28 19:55 UTC, braaAwni submitted a review, later dismissed

2022-04-28 20:04 UTC, nabilramy submitted a review, later dismissed

2022-04-28 20:25 UTC, aaamra requested changes
great job @mo7amedehab97 

but change these file names
- `client/src/Component/Header/Header.css` => `client/src/Component/Header/style.css`

- `client/src/Component/Header/Header.jsx` => `client/src/Component/Header/index.jsx`

- `client/src/Component/Navbar/Navbar.css` => `client/src/Component/Navbar/style.css`

- `client/src/Component/Navbar/Navbar.jsx` => `client/src/Component/Navbar/index.jsx`

2022-04-28 23:31 UTC, nabilramy approved these changes, later dismissed

2022-04-28 23:54 UTC, aaamra approved these changes, later dismissed

2022-04-29 00:02 UTC, KAHMOOSHA approved these changes, later dismissed

2022-05-01 10:13 UTC, braaAwni approved these changes

2022-05-01 11:50 UTC, nabilramy approved these changes

2022-05-01 12:13 UTC, aaamra approved these changes

2022-05-01 12:15 UTC, merged