Husky setup
GSG-G11/Tashteeb pull request #20
Opened 2022-05-01 12:02 UTC by aaamra

- setup husky for eslint and commitlint
- add eslint scripts
- fix eslint error

2022-05-01 12:14 UTC, mo7amedehab97 approved these changes

2022-05-01 14:39 UTC, mo7amedehab97 requested changes
solve conflict

2022-05-04 16:05 UTC, braaAwni submitted a review, later dismissed

2022-05-05 08:14 UTC, nabilramy approved these changes

2022-05-05 08:32 UTC, braaAwni approved these changes

2022-05-05 08:48 UTC, KAHMOOSHA approved these changes

2022-05-05 08:52 UTC, merged