get engineer [home page]
GSG-G11/Tashteeb pull request #40
Opened 2022-05-07 19:38 UTC by braaAwni

![image](https://user-images.githubusercontent.com/91385875/167269269-04b45607-8135-47e9-bfc7-6fa3c929a59c.png)

2022-05-08 17:45 UTC, aaamra requested changes

2022-05-08 17:45 UTC, aaamra commented on client/src/Component/EngineerCard/index.jsx
> +    return () => abortController.abort();
don't use `fetch` anymore use `axios` instead of it
and use the `async` & `await` syntax

2022-05-08 17:45 UTC, aaamra commented on client/src/Component/EngineerCard/index.jsx
> +    return () => abortController.abort();
you can search how to make a `cancelToken` in axios
instead of `AbortController` for clean up

2022-05-09 07:20 UTC, aaamra approved these changes

2022-05-09 07:23 UTC, mo7amedehab97 approved these changes

2022-05-09 11:07 UTC, KAHMOOSHA approved these changes

2022-05-09 11:40 UTC, merged