feat: create protected routes
GSG-G11/Tashteeb pull request #41
Opened 2022-05-07 20:14 UTC by mo7amedehab97

feat: create protected routes

2022-05-08 11:30 UTC, braaAwni submitted a review, later dismissed

2022-05-08 17:08 UTC, nabilramy approved these changes, later dismissed

2022-05-08 17:51 UTC, aaamra requested changes

2022-05-08 17:51 UTC, aaamra commented on client/src/ProtectedRoutes/ProtectedRoutes.jsx
> +  if (!user.user) {
you should check the role for the admin

2022-05-08 17:51 UTC, aaamra commented on client/src/ProtectedRoutes/ProtectedRoutes.jsx
> +  if (user.user.role === 0) {
and here you just want to check if the there is a user in the context
not the user role

2022-05-08 17:51 UTC, aaamra commented on client/src/ProtectedRoutes/ProtectedRoutes.jsx
> +  if (user.user.role === 2) {
as I told you it's not readable to keep the roles as numbers. you can define constants in the useAuth hook to make it more readable

2022-05-08 17:55 UTC, aaamra requested changes

2022-05-08 17:55 UTC, aaamra commented on client/src/ProtectedRoutes/ProtectedRoutes.jsx
> +  if (!user.user) {
in the useAuth hook change it and store just the user in the user state
you are calling `user.user`
keep it simple and make it like this 
```suggestion
  if (!user) {
```

2022-05-08 18:00 UTC, aaamra commented on client/src/ProtectedRoutes/ProtectedRoutes.jsx
> +  if (user.user.role === 2) {
```suggestion
  if (user.role === ENG_ROLE) {
```

2022-05-09 11:45 UTC, aaamra approved these changes

2022-05-09 11:46 UTC, nabilramy approved these changes

2022-05-09 11:47 UTC, KAHMOOSHA approved these changes

2022-05-09 11:52 UTC, braaAwni approved these changes

2022-05-09 11:52 UTC, merged