create dashboard routes
GSG-G11/Tashteeb pull request #57
Opened 2022-05-10 22:17 UTC by mo7amedehab97

create add product route

2022-05-10 23:04 UTC, nabilramy submitted a review, later dismissed

2022-05-11 10:21 UTC, KAHMOOSHA approved these changes, later dismissed

2022-05-11 18:50 UTC, braaAwni approved these changes, later dismissed

2022-05-11 21:41 UTC, aaamra approved these changes

2022-05-11 21:41 UTC, aaamra commented on server/src/controller/products/updateProduct.ts
> +    await product.update(req.body);
where are the validation ?!

2022-05-11 21:43 UTC, aaamra requested changes

2022-05-11 21:43 UTC, aaamra commented on server/src/controller/products/updateProduct.ts
> +    await product.update(req.body);
where are the validation ?!

2022-05-11 21:55 UTC, nabilramy requested changes

2022-05-11 21:55 UTC, nabilramy commented on server/src/controller/products/deleteProduct.ts
> +const deleteProduct = async (req: Request, res: Response) => {
here u need to add the IReqUser that I made previously because the express request doesn't include the user added in middleware.

2022-05-11 21:55 UTC, nabilramy commented on server/src/controller/products/updateProduct.ts
> +const updateProduct = async (req: Request, res: Response) => {
same here

2022-05-15 08:55 UTC, aaamra approved these changes

2022-05-15 08:58 UTC, braaAwni approved these changes

2022-05-15 09:07 UTC, KAHMOOSHA approved these changes

2022-05-15 09:12 UTC, merged