text routes
GSG-G11/Tashteeb pull request #62
Opened 2022-05-12 14:29 UTC by braaAwni

router.get('/engPage', getAllEngineer);
router.get('/eng/:id', gitEngineerById);
router.get('/product/:id', getProducrById);
router.get('/engHome', getEngineer);

2022-05-12 14:54 UTC, mo7amedehab97 requested changes
you need to create tests for the protected routers

2022-05-15 10:49 UTC, aaamra approved these changes, later dismissed

2022-05-15 12:54 UTC, aaamra approved these changes

2022-05-15 19:19 UTC, mo7amedehab97 approved these changes

2022-05-16 07:58 UTC, nabilramy approved these changes

2022-05-16 07:58 UTC, merged