Create Products Page
GSG-G11/Tashteeb pull request #65
Opened 2022-05-14 19:04 UTC by KAHMOOSHA

Created the products page with a search bar and ways to filter products.

2022-05-15 10:58 UTC, nabilramy commented on client/src/Component/EngineerBanner/style.css
> +.engineerDate {
classes names must be kabab not camel case

2022-05-15 10:58 UTC, nabilramy commented on client/src/Component/Filters/filter.css
> +.face__Categories button {
here you are using snake!!

2022-05-15 11:10 UTC, aaamra requested changes

2022-05-15 11:10 UTC, aaamra commented on client/src/Component/Filters/Categories.jsx
> +// eslint-disable-next-line func-names
remove this line

2022-05-15 11:10 UTC, aaamra commented on client/src/Pages/productsPage/index.jsx
> +    });
use async & await syntax and catch the errors

2022-05-15 11:10 UTC, aaamra commented on client/src/Pages/productsPage/index.jsx
> +    };
use async & await syntax and catch the errors

2022-05-17 09:01 UTC, mo7amedehab97 approved these changes

2022-05-17 10:44 UTC, aaamra approved these changes

2022-05-17 10:48 UTC, nabilramy approved these changes

2022-05-17 10:48 UTC, merged