create protected routes
GSG-G11/Tashteeb pull request #89
Opened 2022-05-19 08:26 UTC by mo7amedehab97

create protected routes

- create the dashboard link if the user admin 
- add the navbar to the dashboard page 
- add navbar to the product pages 
- create the protected routes 
- related #86

2022-05-20 22:14 UTC, aaamra requested changes

2022-05-20 22:14 UTC, aaamra commented on client/src/Component/Navbar/index.jsx
> +        {user && <Link to="/dashboard">Dashboard</Link>}
here the user should be an admin to see the dashboard link
so check the admin role not just the user

2022-05-20 22:14 UTC, aaamra commented on client/src/ProtectedRoutes/ProtectedRoutes.jsx
>    if (user) {
if there is no user you should navigate to home page
```suggestion
  if (!user) {
```

2022-05-21 07:52 UTC, mo7amedehab97 commented on client/src/Component/Navbar/index.jsx
> +        {user && <Link to="/dashboard">Dashboard</Link>}
done

2022-05-21 07:52 UTC, mo7amedehab97 commented on client/src/ProtectedRoutes/ProtectedRoutes.jsx
>    if (user) {
done

2022-05-21 08:20 UTC, nabilramy approved these changes, later dismissed

2022-05-21 09:31 UTC, aaamra approved these changes, later dismissed

2022-05-21 11:06 UTC, aaamra approved these changes

2022-05-22 01:08 UTC, nabilramy approved these changes

2022-05-22 07:37 UTC, braaAwni approved these changes

2022-05-22 09:01 UTC, KAHMOOSHA approved these changes

2022-05-22 09:02 UTC, merged