Engineer Component Front
GSG-G11/Tashteeb pull request #9
Opened 2022-04-28 15:35 UTC by braaAwni

![image](https://user-images.githubusercontent.com/91385875/165789928-88c20e4e-b287-47a2-bfd3-e75acb8cb619.png)

2022-04-28 19:53 UTC, mo7amedehab97 approved these changes, later dismissed
nice work braa'

2022-04-28 20:03 UTC, nabilramy submitted a review, later dismissed

2022-04-28 20:18 UTC, aaamra requested changes

2022-04-28 20:18 UTC, aaamra commented on client/src/Component/EngineerCard/index.jsx
> +</div>
extract this to a component

2022-04-28 21:32 UTC, nabilramy submitted a review, later dismissed

2022-05-01 12:02 UTC, mo7amedehab97 submitted a review, later dismissed

2022-05-01 12:04 UTC, aaamra approved these changes, later dismissed

2022-05-01 12:12 UTC, KAHMOOSHA submitted a review, later dismissed

2022-05-04 17:43 UTC, mo7amedehab97 commented on client/src/App.js
>      <div className="App">
where is the app

2022-05-04 17:45 UTC, mo7amedehab97 requested changes
you deleted the pervious work 
updated the main and merge it with your branch then fit your current work with our previous work

2022-05-04 21:42 UTC, mo7amedehab97 approved these changes

2022-05-05 07:02 UTC, aaamra requested changes
fix your eslint errors

2022-05-05 09:54 UTC, nabilramy approved these changes

2022-05-05 09:55 UTC, aaamra approved these changes

2022-05-05 09:55 UTC, mo7amedehab97 approved these changes

2022-05-05 09:57 UTC, merged